[package]
name = "ckb-bench"
version = "0.0.4"
authors = ["keroro <keroroxx520@gmail.com>"]
edition = "2018"

[dependencies]
ckb-testkit = { path = "../ckb-testkit" }

ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
ckb-types = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
ckb-logger-config = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
ckb-logger-service = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
ckb-crypto = { git = "https://github.com/nervosnetwork/ckb.git", rev = "603a811" }
ckb-hash = { git = "https://github.com/nervosnetwork/ckb.git", rev = "603a811" }
clap = { version = "2" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url_serde = "0.2.0"
url = "1.7.2"
toml = "0.5"
lru = "0.6.0"
crossbeam-channel = "0.5.1"
