[package]
name = "ckb-testkit"
version = "0.0.1"
authors = ["keroro <keroroxx520@gmail.com>"]
edition = "2018"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"
description = "ckb testkit"

[dependencies]
ckb2019-jsonrpc-types = { package = "ckb-jsonrpc-types", version = "0.43.2" }
ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
ckb-types = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
ckb-error = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
ckb-crypto = { git = "https://github.com/nervosnetwork/ckb.git", rev = "603a811" }
ckb-hash = { git = "https://github.com/nervosnetwork/ckb.git", rev = "603a811" }
ckb-indexer = { git = "https://github.com/keroro520/ckb-indexer", rev = "f9ce726eacb2dc5cbbfcf9cbd920a8e1d1789257" }
reqwest = { version = "0.10.9", features = ["blocking", "json"] }
serde_json = "1.0"
lazy_static = "1.4.0"
fs_extra = "1.2.0"
jsonrpc-core = "14.0"
log = "0.4"
tempfile = "3.0"
version-compare = "0.0.11"
