name: Fork Tests Checks

on:
  repository_dispatch:
    types: [ fork-tests-checks ]

env:
  CKB_GITHUB_REPOSITORY: ${{ github.event.client_payload.env.ckb_github_repository }}
  CKB_GITHUB_SHA: ${{ github.event.client_payload.env.ckb_github_sha }}

jobs:
  bootstrap:
    name: Bootstrap
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Fork Tests Checks
          status: in_progress

  build-ckb:
    name: Build CKB
    needs: [ bootstrap ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ github.event.client_payload.env.os_matrix }}
      fail-fast: true
      max-parallel: 10
    defaults:
      run:
        working-directory: ckb-integration-test
    steps:
      - uses: actions/checkout@v2
      - if: ${{ runner.os == 'Windows' }}
        run: |
          iex (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

          echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{ github.workspace }}\devtools\windows" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          scoop install git
          scoop bucket add extras
          scoop install llvm yasm
      - name: Build CKB (${{ runner.os }}, ${{ matrix.os }}, ${{ env.CKB_GITHUB_REPOSITORY }}, ${{ env.CKB_GITHUB_SHA }})
        run: make build-ckb
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os != 'Windows' }}
        with:
          name: Released CKB (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/repo/${{ env.CKB_GITHUB_REPOSITORY }}/target/release/ckb
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          name: Released CKB (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/repo/${{ env.CKB_GITHUB_REPOSITORY }}/target/release/ckb.exe
          if-no-files-found: error

  build-ckb-integration-test:
    name: Build CKB-Integration-Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ github.event.client_payload.env.os_matrix }}
      fail-fast: true
      max-parallel: 10
    defaults:
      run:
        working-directory: ckb-integration-test
    steps:
      - uses: actions/checkout@v2
      - if: ${{ runner.os == 'Windows' }}
        run: |
          iex (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

          echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{ github.workspace }}\devtools\windows" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          scoop install git
          scoop bucket add extras
          scoop install llvm yasm
      - name: Build CKB-Integration-Test
        run: make build
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os != 'Windows' }}
        with:
          name: Released CKB-Integration-Test (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/target/release/ckb-integration-test
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          name: Released CKB-Integration-Test (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/target/release/ckb-integration-test.exe
          if-no-files-found: error

  fork-tests:
    name: Fork Tests
    needs: [ build-ckb, build-ckb-integration-test ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ github.event.client_payload.env.os_matrix }}
      fail-fast: false
      max-parallel: 10
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Released CKB (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/testdata/bin
      - uses: actions/download-artifact@v2
        with:
          name: Released CKB-Integration-Test (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/testdata/bin
      - if: ${{ runner.os != 'Windows' }}
        run: |
          cd ./ckb-integration-test
          chmod +x ./testdata/bin/*
          ./testdata/bin/ckb-integration-test run \
            --ckb2021 testdata/bin/ckb
      ## TODO: testdata/db/ is only for Linux and macOS
      # - if: ${{ runner.os == 'Windows' }}
      #   run: |
      #     cd ./ckb-integration-test
      #     chmod +x ./testdata/bin/*
      #     ./testdata/bin/ckb-integration-test.exe run \
      #       --ckb2021 testdata/bin/ckb.exe
      #

  finally:
    name: Finally
    needs: [ fork-tests ]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - if: contains(join(needs.*.result, ';'), 'failure') || contains(join(needs.*.result, ';'), 'cancelled')
        run: exit 1
      - uses: LouisBrunner/checks-action@v1.1.1
        if: ${{ always() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Fork Tests Checks
          status: completed
          conclusion: ${{ job.status }}
