name: Generate Weekly CI Report

# Required secrets:
#
# * `REPO_ACCESS_TOKEN`: (optional) A repo scoped [GitHub Personal Access Token][pat]. See [token] for further details.
#
# [pat]: https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
# [token]: https://github.com/peter-evans/repository-dispatch#token

on:
  # Manurally trigger
  workflow_dispatch:
  schedule:
    - cron: '40 5 * * 2'

jobs:

  repo-access-token:
    name: Check whether REPO_ACCESS_TOKEN is set
    runs-on: ubuntu-latest
    env:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
    outputs:
      is-set: ${{ steps.is-set.outputs.is-set }}
    steps:
      - name: Check is set
        id: is-set
        run: |
          if [ ${#REPO_ACCESS_TOKEN} = 0 ]; then
            echo "::set-output name=is-set::false"
          else
            echo "::set-output name=is-set::true"
          fi

  generate-report:
    name: Generate Weekly CI Report
    if: ${{ needs.repo-access-token.outputs.is-set == 'true' }}
    needs: [ repo-access-token ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r .github/workflows/github-actions-weekly-report/requirements.txt
      - id: generate-report
        run: |
          filename=fork-tests-checks_$(date +'%Y-%m-%d').xlsx
          python3 .github/workflows/github-actions-weekly-report/github-actions-weekly-report.py $filename
          echo "::set-output name=filename::$filename"
        env:
          ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          WORKFLOW: "fork-tests-checks.yml"
      - uses: actions/upload-artifact@v2
        with:
          name: fork-tests-checks
          path: ${{ steps.generate-report.outputs.filename }}
          if-no-files-found: error

  upload-report-to-ckb-assets:
    name: Upload Reprot To nervosnetwork/ckb-assets
    if: needs.repo-access-token.outputs.is-set == 'true' && github.event_name == 'schedule' && github.repository_owner == 'nervosnetwork'
    needs: [ repo-access-token, generate-report ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "nervosnetwork/ckb-assets"
      - uses: actions/download-artifact@v2
        with:
          name: fork-tests-checks
          path: analysis/ci/fork-tests-checks
      - id: get-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commit-message: "[create-pull-request] add fork-tests-checks weekly report"
          branch: "fork-tests-checks"
          branch-suffix: timestamp
          delete-branch: true
          title: "[create-pull-request] add fork-tests-checks weekly report ${{ steps.get-date.outputs.date }}"
      - run: echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
